import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";
import { useState } from "react";
import Image from "next/image";
import Avatar from "../../public/avatar.png";
import Card from "@/components/Card/Card";
import { CardContainer } from "@/styled_components/index.style";
import Store from "../../public/store.png";
import { stores } from "@/data/coffee_store";

export async function getStaticProps(context: any) {
  return {
    props: {
      store_data: stores,
    },
  };
}

const Home: React.FC<any> = ({ store_data }) => {
  const [button_state, setbutton_state] = useState("View nearby coffee shops");
  const onClickButton = () => {
    setTimeout(() => {
      setbutton_state("loading.....");
    }, 2000);
    setbutton_state("View nearby stores");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.main}>
          <Banner buttonText={button_state} onClickButton={onClickButton} />
          <Image
            src={Avatar}
            alt="Avatar"
            style={{ height: 400, width: 600 }}
          />
        </div>

        <CardContainer>
          {store_data?.length > 0 &&
            store_data?.map((store: any) => {
              return (
                <Card
                  name={store.name}
                  href="/coffee-store/new-store"
                  image_url={Store}
                  key={store.id}
                />
              );
            })}
        </CardContainer>
      </div>
    </>
  );
};

export default Home;
